version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: app
    container_name: blog_app_php
    restart: unless-stopped
    volumes:
      - './:/var/www/html'
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: blog_app_nginx
    container_name: blog_app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
      - './docker/nginx/config:/etc/nginx/conf.d/'
    depends_on:
      - app